
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 * JCalc: A Simple calculator
 * 
 */

public class JCalc extends javax.swing.JFrame {

    /**
     * Run the calculator from the command line
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                new JCalc().setVisible(true);
            }
        });
    }

    /**
     * Creates new form JCalc
     */
    public JCalc() {
        initComponents();
        clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel contents = new javax.swing.JPanel();
        display = new javax.swing.JLabel() {
            public java.awt.Dimension getMaximumSize(){
                return new java.awt.Dimension(1000, 30);
            }
        }
        ;
        containorPanel23 = new javax.swing.JPanel();
        javax.swing.JButton digit3 = new javax.swing.JButton();
        javax.swing.JButton digit2 = new javax.swing.JButton();
        containorPanel89 = new javax.swing.JPanel();
        javax.swing.JButton digit8 = new javax.swing.JButton();
        javax.swing.JButton digit9 = new javax.swing.JButton();
        containorPanel56 = new javax.swing.JPanel();
        javax.swing.JButton digit6 = new javax.swing.JButton();
        javax.swing.JButton digit5 = new javax.swing.JButton();
        containorPanel01 = new javax.swing.JPanel();
        javax.swing.JButton digit0 = new javax.swing.JButton();
        javax.swing.JButton decimal = new javax.swing.JButton();
        containorPanelsp = new javax.swing.JPanel();
        javax.swing.JButton signal = new javax.swing.JButton();
        javax.swing.JButton precentage = new javax.swing.JButton();
        containorPanelCE = new javax.swing.JPanel();
        javax.swing.JButton CE = new javax.swing.JButton();
        containorPanel7d = new javax.swing.JPanel();
        javax.swing.JButton digit7 = new javax.swing.JButton();
        javax.swing.JButton divide = new javax.swing.JButton();
        containorPanel4d = new javax.swing.JPanel();
        javax.swing.JButton digit4 = new javax.swing.JButton();
        javax.swing.JButton times = new javax.swing.JButton();
        containorPanel1p = new javax.swing.JPanel();
        javax.swing.JButton digit1 = new javax.swing.JButton();
        javax.swing.JButton plus = new javax.swing.JButton();
        containorPanelem = new javax.swing.JPanel();
        javax.swing.JButton equals = new javax.swing.JButton();
        javax.swing.JButton minus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCalc");
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(285, 400));
        setName("jCalc"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        contents.setBackground(new java.awt.Color(102, 204, 255));
        contents.setAutoscrolls(true);
        contents.setMaximumSize(new java.awt.Dimension(400, 300));
        contents.setPreferredSize(new java.awt.Dimension(285, 400));

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("0");
        display.setAlignmentX(0.5F);
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        display.setFocusable(false);
        display.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        display.setOpaque(true);
        display.setPreferredSize(new java.awt.Dimension(255, 56));
        display.setRequestFocusEnabled(false);

        containorPanel23.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel23.setPreferredSize(new java.awt.Dimension(310, 90));

        digit3.setBackground(new java.awt.Color(51, 102, 255));
        digit3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit3.setForeground(new java.awt.Color(255, 255, 255));
        digit3.setText("3");
        digit3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit3.setPreferredSize(new java.awt.Dimension(60, 60));
        digit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        digit2.setBackground(new java.awt.Color(51, 102, 255));
        digit2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit2.setForeground(new java.awt.Color(255, 255, 255));
        digit2.setText("2");
        digit2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit2.setPreferredSize(new java.awt.Dimension(60, 60));
        digit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel23Layout = new org.jdesktop.layout.GroupLayout(containorPanel23);
        containorPanel23.setLayout(containorPanel23Layout);
        containorPanel23Layout.setHorizontalGroup(
            containorPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel23Layout.createSequentialGroup()
                .add(digit3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(digit2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel23Layout.setVerticalGroup(
            containorPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
            .add(digit2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        containorPanel89.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel89.setPreferredSize(new java.awt.Dimension(310, 90));

        digit8.setBackground(new java.awt.Color(51, 102, 255));
        digit8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit8.setForeground(new java.awt.Color(255, 255, 255));
        digit8.setText("8");
        digit8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        digit8.setPreferredSize(new java.awt.Dimension(60, 60));
        digit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        digit9.setBackground(new java.awt.Color(51, 102, 255));
        digit9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit9.setForeground(new java.awt.Color(255, 255, 255));
        digit9.setText("9");
        digit9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit9.setPreferredSize(new java.awt.Dimension(60, 60));
        digit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel89Layout = new org.jdesktop.layout.GroupLayout(containorPanel89);
        containorPanel89.setLayout(containorPanel89Layout);
        containorPanel89Layout.setHorizontalGroup(
            containorPanel89Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel89Layout.createSequentialGroup()
                .add(digit9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(digit8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel89Layout.setVerticalGroup(
            containorPanel89Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .add(digit8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanel56.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel56.setPreferredSize(new java.awt.Dimension(310, 90));

        digit6.setBackground(new java.awt.Color(51, 102, 255));
        digit6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit6.setForeground(new java.awt.Color(255, 255, 255));
        digit6.setText("6");
        digit6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit6.setPreferredSize(new java.awt.Dimension(60, 60));
        digit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        digit5.setBackground(new java.awt.Color(51, 102, 255));
        digit5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit5.setForeground(new java.awt.Color(255, 255, 255));
        digit5.setText("5");
        digit5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit5.setPreferredSize(new java.awt.Dimension(60, 60));
        digit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel56Layout = new org.jdesktop.layout.GroupLayout(containorPanel56);
        containorPanel56.setLayout(containorPanel56Layout);
        containorPanel56Layout.setHorizontalGroup(
            containorPanel56Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel56Layout.createSequentialGroup()
                .add(digit6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(digit5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel56Layout.setVerticalGroup(
            containorPanel56Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .add(digit5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanel01.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel01.setPreferredSize(new java.awt.Dimension(310, 90));

        digit0.setBackground(new java.awt.Color(51, 102, 255));
        digit0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit0.setForeground(new java.awt.Color(255, 255, 255));
        digit0.setText("0");
        digit0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit0.setPreferredSize(new java.awt.Dimension(60, 60));
        digit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        decimal.setBackground(new java.awt.Color(51, 102, 255));
        decimal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        decimal.setForeground(new java.awt.Color(255, 255, 255));
        decimal.setText(".");
        decimal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decimal.setMaximumSize(new java.awt.Dimension(15, 27));
        decimal.setMinimumSize(new java.awt.Dimension(15, 27));
        decimal.setPreferredSize(new java.awt.Dimension(60, 60));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel01Layout = new org.jdesktop.layout.GroupLayout(containorPanel01);
        containorPanel01.setLayout(containorPanel01Layout);
        containorPanel01Layout.setHorizontalGroup(
            containorPanel01Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel01Layout.createSequentialGroup()
                .add(digit0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(decimal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel01Layout.setVerticalGroup(
            containorPanel01Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
            .add(decimal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanelsp.setBackground(new java.awt.Color(102, 204, 255));
        containorPanelsp.setPreferredSize(new java.awt.Dimension(310, 90));

        signal.setBackground(new java.awt.Color(51, 102, 255));
        signal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        signal.setForeground(new java.awt.Color(255, 255, 255));
        signal.setText("+/-");
        signal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signal.setMaximumSize(new java.awt.Dimension(15, 27));
        signal.setMinimumSize(new java.awt.Dimension(15, 27));
        signal.setPreferredSize(new java.awt.Dimension(60, 60));
        signal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalopActionPerformed(evt);
            }
        });

        precentage.setBackground(new java.awt.Color(51, 102, 255));
        precentage.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        precentage.setForeground(new java.awt.Color(255, 255, 255));
        precentage.setText("%");
        precentage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        precentage.setMaximumSize(new java.awt.Dimension(15, 27));
        precentage.setMinimumSize(new java.awt.Dimension(15, 27));
        precentage.setPreferredSize(new java.awt.Dimension(60, 60));
        precentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageOpActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanelspLayout = new org.jdesktop.layout.GroupLayout(containorPanelsp);
        containorPanelsp.setLayout(containorPanelspLayout);
        containorPanelspLayout.setHorizontalGroup(
            containorPanelspLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanelspLayout.createSequentialGroup()
                .add(signal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(precentage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanelspLayout.setVerticalGroup(
            containorPanelspLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, containorPanelspLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(containorPanelspLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(precentage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .add(signal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        containorPanelCE.setBackground(new java.awt.Color(102, 204, 255));
        containorPanelCE.setPreferredSize(new java.awt.Dimension(310, 90));

        CE.setBackground(new java.awt.Color(51, 102, 255));
        CE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CE.setForeground(new java.awt.Color(255, 255, 255));
        CE.setText("CE");
        CE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CE.setMaximumSize(new java.awt.Dimension(75, 31));
        CE.setMinimumSize(new java.awt.Dimension(75, 31));
        CE.setPreferredSize(new java.awt.Dimension(130, 60));
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear();
            }
        });

        org.jdesktop.layout.GroupLayout containorPanelCELayout = new org.jdesktop.layout.GroupLayout(containorPanelCE);
        containorPanelCE.setLayout(containorPanelCELayout);
        containorPanelCELayout.setHorizontalGroup(
            containorPanelCELayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        containorPanelCELayout.setVerticalGroup(
            containorPanelCELayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanel7d.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel7d.setPreferredSize(new java.awt.Dimension(310, 90));

        digit7.setBackground(new java.awt.Color(51, 102, 255));
        digit7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit7.setForeground(new java.awt.Color(255, 255, 255));
        digit7.setText("7");
        digit7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit7.setPreferredSize(new java.awt.Dimension(60, 60));
        digit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(51, 102, 255));
        divide.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        divide.setForeground(new java.awt.Color(255, 255, 255));
        divide.setText("/");
        divide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divide.setMaximumSize(new java.awt.Dimension(15, 27));
        divide.setMinimumSize(new java.awt.Dimension(15, 27));
        divide.setPreferredSize(new java.awt.Dimension(60, 60));
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel7dLayout = new org.jdesktop.layout.GroupLayout(containorPanel7d);
        containorPanel7d.setLayout(containorPanel7dLayout);
        containorPanel7dLayout.setHorizontalGroup(
            containorPanel7dLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel7dLayout.createSequentialGroup()
                .add(digit7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(divide, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel7dLayout.setVerticalGroup(
            containorPanel7dLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(divide, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanel4d.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel4d.setPreferredSize(new java.awt.Dimension(310, 90));

        digit4.setBackground(new java.awt.Color(51, 102, 255));
        digit4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit4.setForeground(new java.awt.Color(255, 255, 255));
        digit4.setText("4");
        digit4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit4.setPreferredSize(new java.awt.Dimension(60, 60));
        digit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        times.setBackground(new java.awt.Color(51, 102, 255));
        times.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        times.setForeground(new java.awt.Color(255, 255, 255));
        times.setText("*");
        times.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        times.setMaximumSize(new java.awt.Dimension(15, 27));
        times.setMinimumSize(new java.awt.Dimension(15, 27));
        times.setPreferredSize(new java.awt.Dimension(60, 60));
        times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel4dLayout = new org.jdesktop.layout.GroupLayout(containorPanel4d);
        containorPanel4d.setLayout(containorPanel4dLayout);
        containorPanel4dLayout.setHorizontalGroup(
            containorPanel4dLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel4dLayout.createSequentialGroup()
                .add(digit4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(times, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel4dLayout.setVerticalGroup(
            containorPanel4dLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(times, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(digit4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containorPanel1p.setBackground(new java.awt.Color(102, 204, 255));
        containorPanel1p.setPreferredSize(new java.awt.Dimension(310, 90));

        digit1.setBackground(new java.awt.Color(51, 102, 255));
        digit1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        digit1.setForeground(new java.awt.Color(255, 255, 255));
        digit1.setText("1");
        digit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        digit1.setPreferredSize(new java.awt.Dimension(60, 60));
        digit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(51, 102, 255));
        plus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.setToolTipText("Completes current calculation");
        plus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plus.setPreferredSize(new java.awt.Dimension(60, 60));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanel1pLayout = new org.jdesktop.layout.GroupLayout(containorPanel1p);
        containorPanel1p.setLayout(containorPanel1pLayout);
        containorPanel1pLayout.setHorizontalGroup(
            containorPanel1pLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanel1pLayout.createSequentialGroup()
                .add(digit1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(plus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanel1pLayout.setVerticalGroup(
            containorPanel1pLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(digit1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .add(plus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        containorPanelem.setBackground(new java.awt.Color(102, 204, 255));
        containorPanelem.setPreferredSize(new java.awt.Dimension(310, 90));

        equals.setBackground(new java.awt.Color(51, 102, 255));
        equals.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        equals.setForeground(new java.awt.Color(255, 255, 255));
        equals.setText("=");
        equals.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equals.setPreferredSize(new java.awt.Dimension(60, 60));
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(51, 102, 255));
        minus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        minus.setForeground(new java.awt.Color(255, 255, 255));
        minus.setText("-");
        minus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minus.setMaximumSize(new java.awt.Dimension(15, 27));
        minus.setMinimumSize(new java.awt.Dimension(15, 27));
        minus.setPreferredSize(new java.awt.Dimension(60, 60));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout containorPanelemLayout = new org.jdesktop.layout.GroupLayout(containorPanelem);
        containorPanelem.setLayout(containorPanelemLayout);
        containorPanelemLayout.setHorizontalGroup(
            containorPanelemLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containorPanelemLayout.createSequentialGroup()
                .add(equals, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(minus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containorPanelemLayout.setVerticalGroup(
            containorPanelemLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(equals, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(minus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout contentsLayout = new org.jdesktop.layout.GroupLayout(contents);
        contents.setLayout(contentsLayout);
        contentsLayout.setHorizontalGroup(
            contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentsLayout.createSequentialGroup()
                .addContainerGap()
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(display, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .add(contentsLayout.createSequentialGroup()
                        .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, containorPanel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, containorPanel56, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, containorPanelCE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, containorPanel89, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(containorPanel01, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(containorPanel1p, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(containorPanel7d, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(containorPanel4d, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(containorPanelem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .add(containorPanelsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addContainerGap())
        );
        contentsLayout.setVerticalGroup(
            contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentsLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(display, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containorPanelsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .add(containorPanelCE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containorPanel89, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .add(containorPanel7d, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containorPanel56, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .add(containorPanel4d, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containorPanel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .add(containorPanel1p, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containorPanel01, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .add(containorPanelem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(contents);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    /**
     * Clears display and reset's calculator
     */
    private void clear() {
        entering = false;
        result = 0;
        display.setText("0.0");
        operator = '+';
        display.setFont(new java.awt.Font("Arial", 1, Math.min((int)(20+(display.getHeight()/2)),(int)(20+(display.getWidth()/2))))); 
    }

    /**
     * Handler for digit buttons
     *
     * @param evt the ActionEvent
     */
    private void digitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitActionPerformed
        if (!entering) {
            display.setText("");
        }
        display.setText(display.getText() + evt.getActionCommand().charAt(0));
        entering = true;
    }//GEN-LAST:event_digitActionPerformed

    /**
     * Handler for operator buttons
     *
     * @param evt the ActionEvent
     */
    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        float operand = java.lang.Float.parseFloat(display.getText());
        switch (operator) {
            case '+':
                result += operand;
                break;
            case '-':
                result -= operand;
                break;
            case '*':
                result *= operand;
                break;
            case '/':
                result /= operand;
                break;
        }
        display.setText(String.valueOf(result));
        entering = false;
        operator = evt.getActionCommand().charAt(0);
}//GEN-LAST:event_opActionPerformed


    private void signalopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signalopActionPerformed

        float parseRes = Float.parseFloat(display.getText());
        if(parseRes != 0)
        {
            parseRes*=-1;
        }
        display.setText(String.valueOf(parseRes));

    }//GEN-LAST:event_signalopActionPerformed

    private void percentageOpActionPerformed(java.awt.event.ActionEvent evt)
    {
        float operand = java.lang.Float.parseFloat(display.getText());
        result =operand/100;
        operator = '+';
        display.setText(String.valueOf(result));
        entering = false;
    }

    private boolean entering;
    private float result;
    private char operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containorPanel01;
    private javax.swing.JPanel containorPanel1p;
    private javax.swing.JPanel containorPanel23;
    private javax.swing.JPanel containorPanel4d;
    private javax.swing.JPanel containorPanel56;
    private javax.swing.JPanel containorPanel7d;
    private javax.swing.JPanel containorPanel89;
    private javax.swing.JPanel containorPanelCE;
    private javax.swing.JPanel containorPanelem;
    private javax.swing.JPanel containorPanelsp;
    private javax.swing.JLabel display;
    // End of variables declaration//GEN-END:variables
}